"""Verified transcript evidence boundary for Planix Learning."""

from .builders import TranscriptBuildError, TranscriptBuildResult, TranscriptSegmentBuilder
from .evidence_pipeline import (
    TranscriptEvidenceGenerationResult,
    TranscriptEvidencePipeline,
    TranscriptEvidencePipelineError,
)
from .providers import (
    AuthorizedTranscriptPayload,
    AuthorizedTranscriptSource,
    MockTranscriptProvider,
    ParsedSubtitleCue,
    PersistentTranscriptProvider,
    SubtitleFileTranscriptProvider,
    TranscriptDocument,
    TranscriptProvider,
    TranscriptProviderError,
    TranscriptUnavailableError,
    TranscriptSegment,
    TranscriptSourceAdapter,
    TranscriptSourceMetadata,
    SubtitleFormat,
)
from .registry_contracts import (
    NormalizedTranscriptSegment,
    TranscriptFormat,
    TranscriptSourceRecord,
    TranscriptSourceStatus,
    TranscriptSourceSummary,
    TranscriptSourceType,
)
from .repository import (
    LearningTranscriptRepository,
    TranscriptConflict,
    TranscriptRepositoryError,
    TranscriptSourceNotFound,
)
from .services import (
    DEFAULT_TRANSCRIPT_MAX_BYTES,
    HARD_TRANSCRIPT_MAX_BYTES,
    LearningTranscriptRegistrationService,
    TranscriptAcquisitionError,
    TranscriptAcquisitionResult,
    TranscriptAcquisitionStatus,
    TranscriptAcquirer,
    TranscriptRegistrationError,
    configured_transcript_max_bytes,
)
from .validators import TranscriptValidationError, TranscriptValidator

__all__ = [
    "AuthorizedTranscriptPayload",
    "AuthorizedTranscriptSource",
    "MockTranscriptProvider",
    "NormalizedTranscriptSegment",
    "ParsedSubtitleCue",
    "PersistentTranscriptProvider",
    "SubtitleFileTranscriptProvider",
    "SubtitleFormat",
    "TranscriptAcquisitionError",
    "TranscriptAcquisitionResult",
    "TranscriptAcquisitionStatus",
    "TranscriptAcquirer",
    "TranscriptBuildError",
    "TranscriptBuildResult",
    "TranscriptDocument",
    "TranscriptEvidenceGenerationResult",
    "TranscriptEvidencePipeline",
    "TranscriptEvidencePipelineError",
    "TranscriptProvider",
    "TranscriptProviderError",
    "TranscriptUnavailableError",
    "TranscriptSegment",
    "TranscriptSourceAdapter",
    "TranscriptSourceMetadata",
    "TranscriptFormat",
    "TranscriptSourceRecord",
    "TranscriptSourceStatus",
    "TranscriptSourceSummary",
    "TranscriptSourceType",
    "TranscriptSegmentBuilder",
    "TranscriptValidationError",
    "TranscriptValidator",
    "DEFAULT_TRANSCRIPT_MAX_BYTES",
    "HARD_TRANSCRIPT_MAX_BYTES",
    "LearningTranscriptRegistrationService",
    "LearningTranscriptRepository",
    "TranscriptConflict",
    "TranscriptRegistrationError",
    "TranscriptRepositoryError",
    "TranscriptSourceNotFound",
    "configured_transcript_max_bytes",
]
